export const AppStrings = {
  appName: "NESTLUX",
  splash: {
    title: "Find Your Dream Home",
    subtitle: "Extraordinary properties curated for redefined living",
  },
  signin: {
    welcome: "Welcome!",
    description: "Sign in to explore curated properties",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    emailPlaceholder: "sarah@example.com",
    passwordPlaceholder: "••••••••",
    signText: "Sign In",
    forgotPassword: "Forgot Password?",
    signUpPrompt: "Don't have an account?",
    signUpLink: "Sign Up",
    continueWith: "or continue with",
    continueWithGoogle: "Continue with Google",
    signingIn: "Signing In...",
  },
  signup: {
    createAccount: "Create Account",
    pleaseWait: "Please wait...",
    description: "Join thousands of home seekers",
    nameLabel: "Full Name",
    emailLabel: "Email Address",
    emailPlaceholder: "sarah@example.com",
    namePlaceholder: "Sarah Mitchell",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    forgotPassword: "Forgot Password?",
    signInPrompt: "Already have an account?",
    signInLink: "Sign In",
    continueWith: "or continue with",
    continueWithGoogle: "Continue with Google",
  },
  forgotPassword: {
    forgotPasswordText: "Forgot Password",
    description: "Enter your email and we'll send you a verification code",
    emailLabel: "Email Address",
    emailPlaceholder: "sarah@example.com",
    sendCode: "Send Code",
  },
  home: {
    featuredProperties: "Featured Properties",
    seeAll: "See all >",
    ourPicks: "Our Picks",
    featured: "Featured",
  },
  wish: {
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
  },
  picks: {
    all: "All",
    house: "House",
    apartment: "Apartment",
    villa: "Villa",
    studio: "Studio",
  },
  search: {
    placeholder: "Search city, neighborhood...",
  },
  error: "error",
};
